# start this session with:
# kitty --session ~/.config/kitty/sessions/rails_session.conf --title rails

new_tab servers
launch --cwd=~/code_projects/groups-recover-together
launch --cwd=~/code_projects/groups-recover-together --location=vsplit

new_tab code
launch --cwd=~/code_projects/groups-recover-together
launch --cwd=~/code_projects/groups-recover-together --location=vsplit

new_tab claude
launch --cwd=~/code_projects/groups-recover-together
launch --cwd=~/code_projects/groups-recover-together --location=vsplit

new_tab console
launch --cwd=~/code_projects/groups-recover-together
launch --cwd=~/code_projects/groups-recover-together --location=vsplit
