[settings]
idiomatic_version_file_enable_tools = ['node', 'ruby']

[tools]
actionlint = '1.7.7'
direnv = '2.37.0'
elixir = '1.18.4-otp-28'
erlang = '28.0.2'
fd = '10.2.0'
fzf = '0.64.0'
golang = '1.24.5'
jq = '1.6'
lazygit = '0.53.0'
neovim = '0.11.3'
nodejs = '24.4.1'
ripgrep = '14.1.1'
ruby = '3.4.5'
rust = '1.88.0'
shellcheck = '0.10.0'
starship = '1.23.0'
yarn = '4.9.2'
zig = '0.14.1'
