format = """
$username$hostname$directory$git_branch$git_commit$git_state$git_status$package$jobs
$shell$character"""

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[|>](bold green)"
error_symbol = "[|>](bold red)"
vicmd_symbol = "[v:](bold italic fg:blue)"

[directory]
style = "bold purple"

[fill]
style = 'bright-black'
symbol = '─'

[git_branch]
style = "yellow"
symbol = ""

[git_commit]
style = "yellow"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "yellow"
ahead = '[^ ](bold blue)'
behind = '[v ](bold blue)'
conflicted = '[! ](bold #f70067)'
diverged = '[<> ](bold #f70067)'

deleted = '[x ](bold bright-red)'
modified = '[+ ](bold bright-red)'
renamed = '[R ](bold bright-red)'
staged = '[+ ](bold green)'
stashed = '[S ](bold white)'
untracked = '[? ](bold bright-yellow)'

[hostname]
style = "bold #1e4dab"
format = '[$hostname| ]($style)'

[jobs]
symbol = "* "
style = "bold cyan"

[username]
style_root = "bold red"
style_user = "bold #1e4dab"
format = '[$user]($style)[@](dimmed $style)'
